# Generated by Django 5.1.4 on 2026-10-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accepted_privacy_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Acceptation de la politique de confidentialité",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="marketing_opt_in",
            field=models.BooleanField(
                default=False,
                verbose_name="Accepte de recevoir les nouveautés par email",
            ),
        ),
    ]
