# Generated by Django 5.1.4 on 2026-10-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_consent_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_account_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Compte Stripe Connect",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_charges_enabled",
            field=models.BooleanField(default=False, verbose_name="Peut encaisser"),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_payouts_enabled",
            field=models.BooleanField(default=False, verbose_name="Virements activés"),
        ),
    ]
