# Generated by Django 5.1.4 on 2026-10-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_stripe_account_id_user_stripe_charges_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_prefs",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Préférences de notification"
            ),
        ),
    ]
