# Generated by Django 5.1.4 on 2026-10-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_phone_hash_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="code_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
