# Generated by Django 5.1.4 on 2026-06-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('mariage', 'Mariage'), ('conference', 'Conférence'), ('anniversaire', 'Anniversaire'), ('soiree', 'Soirée'), ('concert', 'Concert'), ('seminaire', 'Séminaire'), ('gala', 'Gala'), ('exposition', 'Exposition'), ('festival', 'Festival'), ('atelier', 'Atelier'), ('autre', 'Autre')], max_length=15, verbose_name='Type'),
        ),
    ]
