# Generated by Django 5.1.4 on 2026-10-06 14:51

from decimal import Decimal, InvalidOperation

from django.db import migrations, models


def copy_from_template_config(apps, schema_editor):
    """Remonte is_paid / price / max_guests depuis template_config (ancien stockage)."""
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.exclude(template_config__isnull=True).iterator():
        cfg = event.template_config or {}
        if not isinstance(cfg, dict):
            continue
        changed = False
        if cfg.get('is_paid'):
            event.is_paid = True
            changed = True
        if cfg.get('price') not in (None, ''):
            try:
                event.price = Decimal(str(cfg['price'])).quantize(Decimal('0.01'))
                changed = True
            except (InvalidOperation, ValueError):
                pass
        if cfg.get('max_guests'):
            try:
                event.max_guests = max(1, int(cfg['max_guests']))
                changed = True
            except (TypeError, ValueError):
                pass
        if changed:
            event.save(update_fields=['is_paid', 'price', 'max_guests'])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="currency",
            field=models.CharField(
                default="EUR", max_length=3, verbose_name="Devise (ISO 4217)"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="dress_code",
            field=models.CharField(
                blank=True,
                max_length=80,
                null=True,
                verbose_name="Dress code (ticket, détail, mini-site, email)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Événement payant"),
        ),
        migrations.AddField(
            model_name="event",
            name="max_guests",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre de places (vide = illimité)"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="minisite_config",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Configuration du mini-site"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="0,00 si l'événement est gratuit",
                max_digits=8,
                verbose_name="Prix du ticket",
            ),
        ),
        migrations.RunPython(copy_from_template_config, migrations.RunPython.noop),
    ]
