# Generated by Django 5.1.4 on 2026-10-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_ticketing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type_label",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="Type personnalisé"
            ),
        ),
    ]
