# Generated by Django 5.1.4 on 2026-10-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_type_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ambiance_label",
            field=models.CharField(
                blank=True,
                default="",
                max_length=40,
                verbose_name="Ambiance personnalisée",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="ambiance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("elegant", "Élégant"),
                    ("festif", "Festif"),
                    ("minimaliste", "Minimaliste"),
                    ("colore", "Coloré"),
                    ("professionnel", "Professionnel"),
                    ("autre", "Autre"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
