# Generated by Django 5.2.18 on 2026-10-07 09:08

from django.db import migrations, models
from django.db.models import F


def backfill(apps, schema_editor):
    # Événements déjà publiés : ils comptent dans le quota de leur mois de création
    apps.get_model('events', 'Event').objects.filter(status='published', published_at__isnull=True).update(
        published_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_ambiance_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de première publication"
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
