# Generated by Django 5.2.18 on 2026-10-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="theme",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Thème"
            ),
        ),
    ]
