# Generated by Django 5.2.18 on 2026-10-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="online_link_public",
            field=models.BooleanField(
                default=False, verbose_name="Lien en ligne visible par tous"
            ),
        ),
    ]
