# Generated by Django 5.2.18 on 2026-10-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_online_link_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="video",
            field=models.JSONField(blank=True, null=True, verbose_name="Vidéo"),
        ),
        migrations.AddField(
            model_name="event",
            name="video_public_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
