# Generated by Django 5.2.18 on 2026-10-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="timezone",
            field=models.CharField(
                default="Europe/Paris", max_length=64, verbose_name="Fuseau horaire"
            ),
        ),
    ]
