# Generated by Django 5.2.18 on 2026-10-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="theme",
            field=models.CharField(
                blank=True, default="", max_length=160, verbose_name="Thème"
            ),
        ),
    ]
