# Generated by Django 5.2.18 on 2026-10-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_alter_event_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="assistant_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Réponses automatiques"
            ),
        ),
    ]
