# Generated by Django 5.2.18 on 2026-10-07 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_event_assistant_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendance_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Personnes réellement présentes"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="attendance_reported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="guest_split",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="Répartition des invités par organisateur",
            ),
        ),
        migrations.AddField(
            model_name="eventcollaborator",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventcollaborator",
            name="role",
            field=models.CharField(
                choices=[
                    ("cohost", "Co-organisateur"),
                    ("photographer", "Photographe"),
                ],
                default="cohost",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="eventcollaborator",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("accepted", "Acceptée"),
                    ("declined", "Refusée"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="eventmedia",
            name="caption",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="Légende"
            ),
        ),
        migrations.AddField(
            model_name="eventmedia",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventmedia",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EventComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "-created_at"],
                        name="events_even_event_i_ba55cc_idx",
                    )
                ],
            },
        ),
    ]
