# Generated by Django 5.2.18 on 2026-10-07 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0007_published_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MiniSiteGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("running", "En cours"),
                            ("done", "Terminée"),
                            ("failed", "Échouée"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("step", models.CharField(blank=True, default="", max_length=30)),
                ("engine", models.JSONField(blank=True, default=dict)),
                ("error", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("chosen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minisite_generations",
                        to="events.event",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MiniSiteProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("direction", models.CharField(max_length=20)),
                ("spec", models.JSONField()),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("chosen", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="minisite.minisitegeneration",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
        migrations.AddIndex(
            model_name="minisitegeneration",
            index=models.Index(
                fields=["event", "-created_at"], name="minisite_mi_event_i_81012a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="minisiteproposal",
            constraint=models.UniqueConstraint(
                fields=("generation", "index"), name="minisite_unique_index"
            ),
        ),
    ]
