# Generated by Django 5.2.18 on 2026-10-07 14:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=40)),
                ("target_type", models.CharField(max_length=20)),
                ("target_id", models.CharField(max_length=64)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=90)),
                ("body", models.CharField(blank=True, max_length=400)),
                ("link_url", models.URLField(blank=True, max_length=300)),
                ("link_label", models.CharField(blank=True, max_length=30)),
                ("video_public_id", models.CharField(blank=True, max_length=200)),
                ("video", models.JSONField(blank=True, null=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "Normale"), (50, "Haute"), (90, "Urgente")],
                        default=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-starts_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "starts_at"],
                        name="adminpanel__is_acti_91db2d_idx",
                    )
                ],
            },
        ),
    ]
