# Generated by Django 5.2.18 on 2026-10-07 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("GEMINI_API_KEY", "Google Gemini (IA)"),
                            ("GROQ_API_KEY", "Groq (IA)"),
                            ("OPENROUTER_API_KEY", "OpenRouter (IA)"),
                            ("MISTRAL_API_KEY", "Mistral (IA, direction artistique)"),
                            ("STRIPE_SECRET_KEY", "Stripe — clé secrète"),
                            (
                                "STRIPE_WEBHOOK_SECRET",
                                "Stripe — secret du webhook (whsec_…)",
                            ),
                            (
                                "NOTCHPAY_PUBLIC_KEY",
                                "Notch Pay — clé publique (Mobile Money)",
                            ),
                            (
                                "NOTCHPAY_HASH_KEY",
                                "Notch Pay — clé de hachage des webhooks",
                            ),
                            (
                                "GOOGLE_MAPS_API_KEY",
                                "Google Maps (recherche d’adresses, cartes)",
                            ),
                            ("TWILIO_ACCOUNT_SID", "Twilio — Account SID (SMS)"),
                            ("TWILIO_AUTH_TOKEN", "Twilio — Auth Token (SMS)"),
                            (
                                "TWILIO_MESSAGING_SERVICE_SID",
                                "Twilio — Messaging Service SID",
                            ),
                            ("TWILIO_FROM_NUMBER", "Twilio — numéro d’envoi"),
                            ("SENDGRID_API_KEY", "SendGrid (emails)"),
                            (
                                "CLOUDINARY_CLOUD_NAME",
                                "Cloudinary — nom du cloud (photos, vidéos)",
                            ),
                            ("CLOUDINARY_API_KEY", "Cloudinary — API Key"),
                            ("CLOUDINARY_API_SECRET", "Cloudinary — API Secret"),
                            (
                                "EXPO_ACCESS_TOKEN",
                                "Expo — jeton des notifications push",
                            ),
                        ],
                        max_length=40,
                        unique=True,
                        verbose_name="Service",
                    ),
                ),
                ("encrypted_value", models.TextField(verbose_name="Valeur chiffrée")),
                (
                    "last4",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="4 derniers caractères"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clé de service",
                "verbose_name_plural": "Clés de service (chiffrées)",
                "ordering": ["name"],
            },
        ),
    ]
