# Generated by Django 5.1.4 on 2026-10-07 00:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0006_ambiance_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RsvpQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Texte libre"),
                            ("single", "Choix unique"),
                            ("multiple", "Choix multiple"),
                            ("yesno", "Oui / Non"),
                        ],
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("options", models.JSONField(blank=True, default=list)),
                ("required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvp_questions",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question RSVP",
                "verbose_name_plural": "Questions RSVP",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RsvpAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvp_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="rsvp.rsvpquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse RSVP",
                "verbose_name_plural": "Réponses RSVP",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "user"), name="rsvp_one_answer_per_question"
                    )
                ],
            },
        ),
    ]
