# Generated by Django 5.2.18 on 2026-10-07 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0015_team_memories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "goal_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("allow_items", models.BooleanField(default=True)),
                ("allow_money", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Ouvert"), ("closed", "Fermé")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baskets",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("item", "Objet"), ("money", "Argent")], max_length=5
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("message", models.CharField(blank=True, default="", max_length=200)),
                (
                    "anonymous",
                    models.BooleanField(
                        default=False, verbose_name="Montant masqué aux autres invités"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Ajouté"),
                            ("awaiting_payment", "Paiement en attente"),
                            ("processing", "Paiement en cours"),
                            ("paid", "Payé"),
                            ("failed", "Paiement échoué"),
                            ("cancelled", "Annulé"),
                            ("refunded", "Remboursé"),
                            ("refund_needed", "Remboursement à faire"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "mobile_money_reference",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "mobile_money_amount",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="baskets.basket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basket_contributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="basket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("event",),
                name="basket_one_open_per_event",
            ),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["basket", "status"], name="baskets_con_basket__ea6994_idx"
            ),
        ),
    ]
