# Generated by Django 5.1.4 on 2026-10-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="message",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="message",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "Message"),
                    ("image", "Photo / capture d’écran"),
                    ("location", "Itinéraire"),
                    ("system", "Événement"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
