# Generated by Django 5.2.18 on 2026-10-07 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_theme"),
        ("messaging", "0002_message_attachment_message_meta_alter_message_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "Message"),
                    ("image", "Photo / capture d’écran"),
                    ("location", "Itinéraire"),
                    ("event", "Événement partagé"),
                    ("system", "Événement"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event__isnull", True)),
                fields=("organizer", "participant"),
                name="conversation_unique_direct",
            ),
        ),
    ]
