# Generated by Django 5.2.18 on 2026-10-07 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_event_assistant_enabled"),
        ("messaging", "0003_direct_conversations"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField(blank=True, default="", max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("auto", "Réponse automatique"),
                            ("pending", "En attente de l'organisateur"),
                            ("answered", "Répondue par l'organisateur"),
                        ],
                        max_length=10,
                    ),
                ),
                ("source", models.CharField(blank=True, default="", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="messaging.conversation",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="events.event",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "status"],
                        name="messaging_e_event_i_1306b4_idx",
                    )
                ],
            },
        ),
    ]
