# Generated by Django 5.1.4 on 2026-10-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="contact_name",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Nom du contact"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "En cours"),
                    ("sent", "Envoyé"),
                    ("failed", "Échec"),
                    ("not_configured", "Canal non configuré"),
                    ("in_app", "Dans l'application"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email invité"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="message",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Message personnalisé",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="phone_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="Empreinte HMAC du numéro",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="remind_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="invitation",
            name="reminded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernière relance"
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="channel",
            field=models.CharField(
                choices=[
                    ("sms", "SMS (via Twilio)"),
                    ("email", "Email (M30)"),
                    ("platform_notification", "Notification in-app"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Numéro de téléphone (chiffré)",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="token",
            field=models.CharField(
                help_text="Jeton généré avec secrets.token_urlsafe(32), stocké haché",
                max_length=64,
                unique=True,
                verbose_name="Empreinte SHA-256 du token (256 bits)",
            ),
        ),
    ]
