# Generated by Django 5.1.4 on 2026-10-07 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0003_secure_existing_data"),
        ("rsvp", "0002_copy_legacy_rsvp"),     # données recopiées avant suppression
    ]

    # Les questions RSVP vivent désormais dans l'app « rsvp » (voir rsvp/0002)
    operations = [
        migrations.DeleteModel(name="RSVPResponse"),
        migrations.DeleteModel(name="RSVPQuestion"),
    ]
