# Generated by Django 5.1.4 on 2026-10-06 23:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "En attente"), ("accepted", "Amis")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "addressee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "friendships",
                "indexes": [
                    models.Index(
                        fields=["addressee", "status"],
                        name="friendships_address_4da91f_idx",
                    ),
                    models.Index(
                        fields=["requester", "status"],
                        name="friendships_request_74cfa7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("requester", "addressee"), name="friendship_unique_pair"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("requester", models.F("addressee")), _negated=True
                        ),
                        name="friendship_not_self",
                    ),
                ],
            },
        ),
    ]
