# Generated by Django 5.1.4 on 2026-10-06 18:42

import django.db.models.deletion
import tickets.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0006_ambiance_label"),
        ("invitations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        default=tickets.models.new_ticket_number,
                        editable=False,
                        max_length=11,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("generated", "Généré"),
                            ("cancelled", "Annulé"),
                            ("expired", "Expiré"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Gratuit"),
                            ("pending", "En attente de paiement"),
                            ("processing", "Paiement en cours de confirmation"),
                            ("paid", "Payé"),
                            ("failed", "Paiement échoué"),
                            ("refunded", "Remboursé"),
                        ],
                        default="not_required",
                        max_length=12,
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("dress_code", models.CharField(blank=True, default="", max_length=80)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="events.event",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="invitations.invitation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tickets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="tickets_user_id_88df9d_idx"
                    ),
                    models.Index(
                        fields=["event", "status"], name="tickets_event_i_30e5cd_idx"
                    ),
                    models.Index(
                        fields=["stripe_checkout_session_id"],
                        name="tickets_stripe__978508_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "generated"])),
                        fields=("event", "user"),
                        name="one_active_ticket_per_event_user",
                    )
                ],
            },
        ),
    ]
