# Generated by Django 5.2.18 on 2026-10-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
