# Generated by Django 5.2.18 on 2026-10-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_checked_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="mobile_money_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="mobile_money_reference",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
