# Generated by Django 5.2.18 on 2026-10-07 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_alter_event_theme"),
        ("tickets", "0003_ticket_mobile_money_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="purchased_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_offered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TicketGift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "recipient_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "recipient_phone",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "recipient_phone_hash",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("message", models.CharField(blank=True, default="", max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_payment", "En attente de paiement"),
                            ("paid", "Payé, en attente du proche"),
                            ("delivered", "Remis au proche"),
                            ("cancelled", "Annulé"),
                            ("refund_needed", "À rembourser"),
                        ],
                        default="awaiting_payment",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Gratuit"),
                            ("pending", "En attente de paiement"),
                            ("processing", "Paiement en cours de confirmation"),
                            ("paid", "Payé"),
                            ("failed", "Paiement échoué"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "mobile_money_reference",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "mobile_money_amount",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts",
                        to="events.event",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gifts_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_email", "status"],
                        name="tickets_tic_recipie_8e383f_idx",
                    ),
                    models.Index(
                        fields=["buyer", "status"],
                        name="tickets_tic_buyer_i_f20f69_idx",
                    ),
                ],
            },
        ),
    ]
