# Generated by Django 5.1.4 on 2026-10-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("events", "Événements"),
                    ("messages", "Messages"),
                    ("system", "Système"),
                    ("social", "Amis"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("invitation_received", "Invitation reçue"),
                    ("ticket_to_validate", "Ticket à valider"),
                    ("ticket_generated", "Ticket généré"),
                    ("message_received", "Nouveau message"),
                    ("daily_summary", "Bilan du jour"),
                    ("reminder", "Rappel"),
                    ("payment_succeeded", "Paiement confirmé"),
                    ("payment_failed", "Paiement échoué"),
                    ("friend_request", "Demande d'ami"),
                    ("friend_accepted", "Demande acceptée"),
                ],
                max_length=30,
            ),
        ),
    ]
