# Generated by Django 5.1.4 on 2026-10-07 03:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_category_alter_notification_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("invitation_received", "Invitation reçue"),
                    ("ticket_to_validate", "Ticket à valider"),
                    ("ticket_generated", "Ticket généré"),
                    ("message_received", "Nouveau message"),
                    ("daily_summary", "Bilan du jour"),
                    ("reminder", "Rappel"),
                    ("payment_succeeded", "Paiement confirmé"),
                    ("payment_failed", "Paiement échoué"),
                    ("friend_request", "Demande d'ami"),
                    ("friend_accepted", "Demande acceptée"),
                    ("guest_response", "Réponse d'un invité"),
                    ("event_full", "Événement complet"),
                    ("payouts_ready", "Paiements activés"),
                    ("event_updated", "Événement modifié"),
                    ("event_cancelled", "Événement annulé"),
                    ("invitation_revoked", "Invitation retirée"),
                    ("payment_refunded", "Remboursement"),
                    ("subscription", "Abonnement"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("platform", models.CharField(blank=True, default="", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "device_tokens",
            },
        ),
    ]
