# Generated by Django 5.2.18 on 2026-10-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("invitation_received", "Invitation reçue"),
                    ("ticket_to_validate", "Ticket à valider"),
                    ("ticket_generated", "Ticket généré"),
                    ("message_received", "Nouveau message"),
                    ("daily_summary", "Bilan du jour"),
                    ("reminder", "Rappel"),
                    ("payment_succeeded", "Paiement confirmé"),
                    ("payment_failed", "Paiement échoué"),
                    ("friend_request", "Demande d'ami"),
                    ("friend_accepted", "Demande acceptée"),
                    ("guest_response", "Réponse d'un invité"),
                    ("event_full", "Événement complet"),
                    ("payouts_ready", "Paiements activés"),
                    ("event_updated", "Événement modifié"),
                    ("event_cancelled", "Événement annulé"),
                    ("invitation_revoked", "Invitation retirée"),
                    ("payment_refunded", "Remboursement"),
                    ("subscription", "Abonnement"),
                    ("minisite_ready", "Mini-site prêt"),
                    ("ticket_gift", "Billet offert"),
                    ("question_to_answer", "Question à laquelle répondre"),
                    ("team_invite", "Invitation à co-organiser"),
                    ("team_response", "Réponse d'un co-organisateur"),
                    ("event_broadcast", "Message à tous les invités"),
                    ("event_comment", "Nouveau commentaire"),
                    ("memories_added", "Nouvelles photos souvenirs"),
                    ("basket_open", "Panier ouvert"),
                    ("basket_contribution", "Ajout au panier"),
                ],
                max_length=30,
            ),
        ),
    ]
